name = "backend"
compatibility_date = "2023-12-01"

 [vars]
 DATABASE="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2VjNjI2N2MtNjI3MC00ZmU4LThjNTEtMjMyNmMzNWQ0NDczIiwidGVuYW50X2lkIjoiZmI4ODU1ZWNmNGEzM2I0ZmZhMzc5MDNiYzE4ZmNjZWZiMjEwM2YwZjVmZWM3OWFiNGJkMzE2ODY2OGY0ZWViOSIsImludGVybmFsX3NlY3JldCI6ImFiNzA4NGRkLTY2ZmMtNDk1OC1hYTAwLWZmOTU3NWExMTcxNSJ9.g_bZw8w84egWcc3_NJoROjrnA3g7RGGFZeZf1qtxiAg"

JWT_SECRET="eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwODk2NDM4OCwiaWF0IjoxNzA4OTY0Mzg4fQ.v2gep3UtDpr3_zJp70lFW3RvY5-GWS5qMDHw9JJjev5kb_ZTSrfFpe1645cp_ij8Ix_dkLCgUwbA-6utC7qX8A"


[dev]
port = 8080